### ISSUE TITLE
IpTablesParserException Unknown option: "--random-fully"

### ISSUE THREAD

**Issue by wlclass** [splitice/IPTables.Net#9]
Thank you for a great job.👍
When I tested it on Ubuntu 20.04.3 LTS \ iptables v1.8.4 (legacy)   .
```csharp
var sys = new IpTablesSystem(new LocalFactory(), new IPTablesBinaryAdapter());
var chain = sys.GetChain("nat", "PREROUTING", 4);
```
I got an error :
```bash
IPTables.Net.Exceptions.IpTablesParserException: Error parsing rule:  -A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
 ---> IPTables.Net.Exceptions.IpTablesNetException: Unknown option: "--random-fully"
   at IPTables.Net.Iptables.Modules.CommandParser.FeedToSkip(Int32 position, Boolean not)
   at IPTables.Net.Iptables.IpTablesCommand.Parse(String rule, IpTablesSystem system, IpTablesChainSet chains, CommandParser& parserOut, Int32 version, String defaultTable)
   --- End of inner exception stack trace ---
   at IPTables.Net.Iptables.IpTablesCommand.Parse(String rule, IpTablesSystem system, IpTablesChainSet chains, CommandParser& parserOut, Int32 version, String defaultTable)
   at IPTables.Net.Iptables.IpTablesRule.Parse(String rule, IpTablesSystem system, IpTablesChainSet chains, Int32 version, String defaultTable, ChainCreateMode createChain)
   at IPTables.Net.Iptables.Adapter.Client.Helper.IPTablesSaveParser.GetRulesFromOutput(IpTablesSystem system, String output, String table, Int32 ipVersion, Boolean ignoreErrors)
   at IPTables.Net.Iptables.Adapter.Client.IPTablesBinaryAdapterClient.ListRules(String table)
   at IPTables.Net.IpTablesSystem.GetRules(IIPTablesAdapterClient client, String table)
   at IPTables.Net.IpTablesSystem.GetChain(IIPTablesAdapterClient client, String table, String chain)
   at IPTables.Net.IpTablesSystem.GetChain(String table, String chain, Int32  ipVersion)

```

**Comment by splitice** [comment]
Yes an unsupported option ro masqerade you can add. Acceptable PRs accepted.

**Comment by wlclass** [comment]
ok,thanks.
I need to continue learning your project.
